delta_bank_updated/delta_bank/bank_app/urls.py
from django.urls import path, include
from . import views
#from .api import Transfer
#from bank_app.views import (RegisterView, LoginView,GenerateOTP, VerifyOTP, ValidateOTP, DisableOTP)



app_name = "bank_app"

urlpatterns = [
    path('', views.index, name='index'),
    #path('login', views.login_view, name='login'),


    path('dashboard/', views.dashboard, name='dashboard'),
    path('account_details/<int:pk>/', views.account_details, name='account_details'),
    path('transaction_details/<uuid:transaction>/', views.transaction_details, name='transaction_details'),
    path('make_transfer/', views.make_transfer, name='make_transfer'),
    path('make_loan/', views.make_loan, name='make_loan'),
    path('settings/', views.settings, name='settings'),

    path('staff_dashboard/', views.staff_dashboard, name='staff_dashboard'),
    path('staff_search_partial/', views.staff_search_partial, name='staff_search_partial'),
    path('staff_customer_details/<int:pk>/', views.staff_customer_details, name='staff_customer_details'),
    path('staff_account_list_partial/<int:pk>/', views.staff_account_list_partial, name='staff_account_list_partial'),
    path('staff_account_details/<int:pk>/', views.staff_account_details, name='staff_account_details'),
    path('staff_new_account_partial/<int:user>/', views.staff_new_account_partial, name='staff_new_account_partial'),
    path('staff_new_customer/', views.staff_new_customer, name='staff_new_customer'),

    #messages
    path('message/', views.message, name='message'),
    path('message_detail/<int:pk>/', views.message_detail, name='message_detail'),

    #API
    path('api/v1/make_transfer/from/', views.transfer_money_from),
    path('api/v1/make_transfer/to/', views.transfer_money_to),
    path('api/v1/credit_acc_validation/', views.credit_acc_validation),
]

delta_bank_updated/delta_bank/delta_bank/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('bank_app.urls')),
    path('api/auth/', include('mfa_app.urls')),
]

delta_bank_updated/delta_bank/mfa_app/urls.py
from . import views
from django.urls import path, include
from mfa_app.views import (RegisterView, LoginView,GenerateOTP, VerifyOTP, ValidateOTP, DisableOTP)  

app_name = "mfa_app"

urlpatterns = [

    path('login', views.login_view, name='login'),
    #2FA
    path('register', RegisterView.as_view()),
    path('login', LoginView.as_view()),
    path('otp/generate', GenerateOTP.as_view()),
    path('otp/verify', VerifyOTP.as_view()),
    path('otp/validate', ValidateOTP.as_view()),
    path('otp/disable', DisableOTP.as_view()),
]

delta_bank_updated/delta_bank/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'simple.css' %}" media="screen" />
    <title>Delta Bank</title>
</head>
<body>

    {% load l10n %}

    <header>
        <h1>Delta Bank</h1>
        {% if user.is_staff %}
        <h2>Bank Staff Portal</h2>
        {% else %}
        <h2>Bank Customer Portal</h2>
        {% endif %}
    </header>

    <nav>
        <ul>
            <li><a href="{% url 'bank_app:index' %}">Home</a></li>
            
            
                
            {% if user.is_superuser %}
            <li><a href="{% url 'admin:index' %}">Admin</a></li>
            {% endif %}
            
                
            
            {% if user.is_staff %}
                <li><a href="{% url 'bank_app:staff_new_customer' %}">New Customer</a></li>
                <li><a href="{% url 'bank_app:message' %}">Inbox</a></li>
                <li><a href="{% url 'logout' %}">Log out</a></li>
                <li><a href="{% url 'bank_app:settings' %}">Settings</a></li>
            {% elif user.username %}
                <li><a href="{% url 'bank_app:make_transfer' %}">Make Transfer</a></li>
                <li><a href="{% url 'bank_app:make_loan' %}">Make Loan</a></li>
                <li><a href="{% url 'bank_app:message' %}">Inbox</a></li>
                <li><a href="{% url 'logout' %}">Log out</a></li>
                <li><a href="{% url 'bank_app:settings' %}">Settings</a></li>
            {% endif %}
            
        </ul>
    </nav>

    <main>
    {% block main %}
    {% endblock main %}
    </main>

    <footer>
        <p>Group: Delta - kea exam</p>
    </footer>
    <script src="https://unpkg.com/htmx.org@1.5.0" integrity="sha384-oGA+prIp5Vchu6we2YkI51UtVzN9Jpx2Z7PnR1I78PnZlN8LkrCT4lqqqmDkyrvI" crossorigin="anonymous"></script>
    <script>
        document.body.addEventListener('htmx:configRequest', (event) => {
            event.detail.headers['X-CSRFToken'] = '{{ csrf_token }}';
        })
    </script>
</body>
</html>