delta_bank_updated/delta_bank/bank_app/urls.py
from django.urls import path, include
from . import views
#from .api import Transfer
#from bank_app.views import (RegisterView, LoginView,GenerateOTP, VerifyOTP, ValidateOTP, DisableOTP)



app_name = "bank_app"

urlpatterns = [
    path('', views.index, name='index'),
    #path('login', views.login_view, name='login'),


    path('dashboard/', views.dashboard, name='dashboard'),
    path('account_details/<int:pk>/', views.account_details, name='account_details'),
    path('transaction_details/<uuid:transaction>/', views.transaction_details, name='transaction_details'),
    path('make_transfer/', views.make_transfer, name='make_transfer'),
    path('make_loan/', views.make_loan, name='make_loan'),
    path('settings/', views.settings, name='settings'),

    path('staff_dashboard/', views.staff_dashboard, name='staff_dashboard'),
    path('staff_search_partial/', views.staff_search_partial, name='staff_search_partial'),
    path('staff_customer_details/<int:pk>/', views.staff_customer_details, name='staff_customer_details'),
    path('staff_account_list_partial/<int:pk>/', views.staff_account_list_partial, name='staff_account_list_partial'),
    path('staff_account_details/<int:pk>/', views.staff_account_details, name='staff_account_details'),
    path('staff_new_account_partial/<int:user>/', views.staff_new_account_partial, name='staff_new_account_partial'),
    path('staff_new_customer/', views.staff_new_customer, name='staff_new_customer'),

    #messages
    path('message/', views.message, name='message'),
    path('message_detail/<int:pk>/', views.message_detail, name='message_detail'),

    #API
    path('api/v1/make_transfer/from/', views.transfer_money_from),
    path('api/v1/make_transfer/to/', views.transfer_money_to),
    path('api/v1/credit_acc_validation/', views.credit_acc_validation),
]

delta_bank_updated/delta_bank/delta_bank/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('bank_app.urls')),
    path('api/auth/', include('mfa_app.urls')),
]

delta_bank_updated/delta_bank/mfa_app/urls.py
from . import views
from django.urls import path, include
from mfa_app.views import (RegisterView, LoginView,GenerateOTP, VerifyOTP, ValidateOTP, DisableOTP)  

app_name = "mfa_app"

urlpatterns = [

    path('login', views.login_view, name='login'),
    #2FA
    path('register', RegisterView.as_view()),
    path('login', LoginView.as_view()),
    path('otp/generate', GenerateOTP.as_view()),
    path('otp/verify', VerifyOTP.as_view()),
    path('otp/validate', ValidateOTP.as_view()),
    path('otp/disable', DisableOTP.as_view()),
]

delta_bank_updated/delta_bank/bank_app/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.core.exceptions import ObjectDoesNotExist
from .models import Customer, Account, Message

User = get_user_model()

class TransferForm(forms.Form):
    amount  = forms.DecimalField(label='Amount', max_digits=10)
    debit_account = forms.ModelChoiceField(label='Debit Account', queryset=Customer.objects.none())
    debit_text = forms.CharField(label='Debit Account Text', max_length=25)
    credit_account = forms.CharField(label='Credit Account Number', max_length=20)
    credit_text = forms.CharField(label='Credit Account Text', max_length=25)

    def clean(self):
        super().clean()

        # Ensure credit account exist
        credit_account = self.cleaned_data.get('credit_account')
        # try:
        #     Account.objects.get(pk=credit_account)
        # except ObjectDoesNotExist:
        #     self._errors['credit_account'] = self.error_class(['Credit account does not exist.'])

        # Ensure positive amount
        if self.cleaned_data.get('amount') < 0:
            self._errors['amount'] = self.error_class(['Amount must be positive.'])

        return self.cleaned_data


class NewUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email')

    def clean(self):
        super().clean()
        username = self.cleaned_data.get('username')
        if User.objects.filter(username=username):
            self._errors['username'] = self.error_class(['Username already exists.'])
        return self.cleaned_data


class UserForm(forms.ModelForm):
    username = forms.CharField(label='Username', disabled=True)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email')

class CustomerForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = ('rank', 'personal_id', 'phone')

class NewAccountForm(forms.ModelForm):
    class Meta:
        model = Account
        fields = ('name',)

class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ('receiver', 'content')
        widgets = {
            'receiver': forms.Select(attrs={'class': 'form-control'}),
            'content': forms.Textarea(attrs={'class': 'form-control'}),
        }

    def __init__(self, current_user, is_staff, *args, **kwargs):
        super(MessageForm, self).__init__(*args, **kwargs)
        if(is_staff):
            self.fields['receiver'].queryset = User.objects.exclude(is_staff=True).exclude(pk=current_user.pk)
        else:
            self.fields['receiver'].queryset = User.objects.exclude(is_staff=False).exclude(pk=current_user.pk)

#Til csrf token
class Otp_form(forms.Form):
    my_hidden_field = forms.CharField(widget=forms.HiddenInput())

delta_bank_updated/delta_bank/bank_app/views.py
from decimal import Decimal
from secrets import token_urlsafe
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import render, reverse, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, get_user_model
from django.core.exceptions import PermissionDenied, ObjectDoesNotExist
from django.db import IntegrityError
from .forms import TransferForm, UserForm, CustomerForm, NewUserForm, NewAccountForm, MessageForm, Otp_form
from .models import Account, Ledger, Customer, Message, User
from .errors import InsufficientFunds
from .serializers import UserSerializer
import pyotp
from rest_framework import generics, permissions, status
from rest_framework.response import Response
from rest_framework.decorators import api_view

User = get_user_model()


@login_required
def index(request):
    if request.user.is_staff:
        return HttpResponseRedirect(reverse('bank_app:staff_dashboard'))
    else:
        return HttpResponseRedirect(reverse('bank_app:dashboard'))


# Customer views

@login_required
def dashboard(request):
    assert not request.user.is_staff, 'Staff user routing customer view.'

    accounts = request.user.customer.accounts
    context = {
        'accounts': accounts,
    }
    return render(request, 'bank_app/dashboard.html', context)


@login_required
def account_details(request, pk):
    assert not request.user.is_staff, 'Staff user routing customer view.'

    account = get_object_or_404(Account, user=request.user, pk=pk)
    context = {
        'account': account,
    }
    return render(request, 'bank_app/account_details.html', context)


@login_required
def transaction_details(request, transaction):
    movements = Ledger.objects.filter(transaction=transaction)
    if not request.user.is_staff:
        if not movements.filter(account__in=request.user.customer.accounts):
            raise PermissionDenied('Customer is not part of the transaction.')
    context = {
        'movements': movements,
    }
    return render(request, 'bank_app/transaction_details.html', context)


@login_required
def make_transfer(request):
    assert not request.user.is_staff, 'Staff user routing customer view.'

    form = TransferForm()
    form.fields['debit_account'].queryset = request.user.customer.accounts
    context = {
        'form': form,
    }
    return render(request, 'bank_app/make_transfer.html', context)


@login_required
def make_loan(request):
    assert not request.user.is_staff, 'Staff user routing customer view.'

    if not request.user.customer.can_make_loan:
        context = {
            'title': 'Create Loan Error',
            'error': 'Loan could not be completed.'
        }
        return render(request, 'bank_app/error.html', context)
    if request.method == 'POST':
        request.user.customer.make_loan(Decimal(request.POST['amount']), request.POST['name'])
        return HttpResponseRedirect(reverse('bank_app:dashboard'))
    return render(request, 'bank_app/make_loan.html', {})


# Staff views

@login_required
def staff_dashboard(request):
    assert request.user.is_staff, 'Customer user routing staff view.'

    return render(request, 'bank_app/staff_dashboard.html')


@login_required
def staff_search_partial(request):
    assert request.user.is_staff, 'Customer user routing staff view.'

    search_term = request.POST['search_term']
    customers = Customer.search(search_term)
    context = {
        'customers': customers,
    }
    return render(request, 'bank_app/staff_search_partial.html', context)


@login_required
def staff_customer_details(request, pk):
    assert request.user.is_staff, 'Customer user routing staff view.'

    customer = get_object_or_404(Customer, pk=pk)
    if request.method == 'GET':
        user_form = UserForm(instance=customer.user)
        customer_form = CustomerForm(instance=customer)
    elif request.method == 'POST':
        user_form = UserForm(request.POST, instance=customer.user)
        customer_form = CustomerForm(request.POST, instance=customer)
        if user_form.is_valid() and customer_form.is_valid():
            user_form.save()
            customer_form.save()
    new_account_form = NewAccountForm()
    context = {
        'customer': customer,
        'user_form': user_form,
        'customer_form': customer_form,
        'new_account_form': new_account_form,
    }
    return render(request, 'bank_app/staff_customer_details.html', context)


@login_required
def staff_account_list_partial(request, pk):
    assert request.user.is_staff, 'Customer user routing staff view.'

    customer = get_object_or_404(Customer, pk=pk)
    accounts = customer.accounts
    context = {
        'accounts': accounts,
    }
    return render(request, 'bank_app/staff_account_list_partial.html', context)


@login_required
def staff_account_details(request, pk):
    assert request.user.is_staff, 'Customer user routing staff view.'

    account = get_object_or_404(Account, pk=pk)
    context = {
        'account': account,
    }
    return render(request, 'bank_app/account_details.html', context)


@login_required
def staff_new_account_partial(request, user):
    assert request.user.is_staff, 'Customer user routing staff view.'

    if request.method == 'POST':
        new_account_form = NewAccountForm(request.POST)
        if new_account_form.is_valid():
            Account.objects.create(user=User.objects.get(pk=user), name=new_account_form.cleaned_data['name'])
    return HttpResponseRedirect(reverse('bank_app:staff_customer_details', args=(user,)))


@login_required
def staff_new_customer(request):
    assert request.user.is_staff, 'Customer user routing staff view.'

    if request.method == 'POST':
        new_user_form = NewUserForm(request.POST)
        customer_form = CustomerForm(request.POST)
        if new_user_form.is_valid() and customer_form.is_valid():
            username    = new_user_form.cleaned_data['username']
            first_name  = new_user_form.cleaned_data['first_name']
            last_name   = new_user_form.cleaned_data['last_name']
            email       = new_user_form.cleaned_data['email']
            password    = token_urlsafe(16)
            rank        = customer_form.cleaned_data['rank']
            personal_id = customer_form.cleaned_data['personal_id']
            phone       = customer_form.cleaned_data['phone']
            try:
                user = User.objects.create_user(
                        username=username,
                        password=password,
                        email=email,
                        first_name=first_name,
                        last_name=last_name
                )
                print(f'********** Username: {username} -- Password: {password}')
                Customer.objects.create(user=user, rank=rank, personal_id=personal_id, phone=phone)
                return staff_customer_details(request, user.pk)
            except IntegrityError:
                context = {
                    'title': 'Database Error',
                    'error': 'User could not be created.'
                }
                return render(request, 'bank_app/error.html', context)
    else:
        new_user_form = NewUserForm()
        customer_form = CustomerForm()
    context = {
        'new_user_form': new_user_form,
        'customer_form': customer_form,
    }
    return render(request, 'bank_app/staff_new_customer.html', context)

@login_required
def message(request):
    
    if request.method == 'POST':
        sender = request.user
        receiver_id = request.POST.get("receiver")
        receiver = User.objects.get(pk=receiver_id)
        content = request.POST.get("content")
        try :
            Message.objects.create(sender = sender, receiver = receiver, content = content)
            return index(request)
        except IntegrityError:
            context = {
                'title': 'Database Error',
                'error': 'User could not be created.'
            }
            return render(request, 'bank/error.html', context)
       
    else:
        form = MessageForm(current_user=request.user, is_staff=request.user.is_staff)

    messages = Message.objects.filter(receiver=request.user)
    users = User.objects.exclude(id=request.user.id)
    return render(request, 'bank_app/inbox.html', {'form': form, 'messages': messages, 'users': users})

def message_detail(request, pk):
    message = get_object_or_404(Message, pk=pk)
    return render(request, 'bank_app/message.html', {'message': message})

@login_required
def settings(request):
    
    form = Otp_form()

    context = {
        'otp_verified': request.user.otp_verified,
        'user_id': request.user.id,
        'email': request.user.email,
        'form': form #Sender for med for at csrf token kan bruges
    }
    return render(request, 'bank_app/settings.html', context)


# --------------API-------------

#Check om credit konto eksisterer før der fortages en overførelse
@api_view(['POST'])
def credit_acc_validation(request):

    if request.method == 'POST':

        credit_account = request.POST['credit_account']
        print(credit_account)
        try:
            if Account.objects.get(pk=credit_account):
                return JsonResponse({"message": "account found"}, status=200)
        except ObjectDoesNotExist:
            return JsonResponse({"message": "account not found"}, status=403)


#API der fratrækker penge fra senders konto
@api_view(['POST'])
def transfer_money_from(request):

    if request.method == 'POST':
        amount = int(request.POST['amount'])
        debit_account = Account.objects.get(pk=request.POST['debit_account'])
        debit_text = request.POST['debit_text']

        try:
            transfer = Ledger.transfer_from(amount, debit_account, debit_text)
            return JsonResponse({"unique_id": transfer}, status=200) #Sender UUID tilbage til client

delta_bank_updated/delta_bank/bank_app/templates/bank_app/account_details.html
{% extends "base.html" %}

{% block main %}

{% if user.is_staff %}
<p>Welcome, {{ user }}.</p>
{% else %}
<p>Welcome, {{ user.customer.full_name }}.</p>
{% endif %}

<h3>Account Details</h3>

<table>
    <tr>
        <th>Account Number</th>
        <th>Account Name</th>
        <th>Balance</th>
    </tr>
    <tr>
        <td>{{ account.pk }}</td>
        <td>{{ account.name }}</td>
        <td class="amount">{{ account.balance|floatformat:"2" }}</td>
    </tr>
</table>

<h3>Account Transactions</h3>

<table>
    <tr>
        <th>Transaction UUID</th>
        <th>Amount</th>
        <th>Date and Time</th>
        <th>Text</th>
    </tr>
    {% for movement in account.movements %}
    <tr>
        <td><a href="{% url 'bank_app:transaction_details' movement.transaction %}">{{ movement.transaction }}</a></td>
        <td>{{ movement.amount|floatformat:"2" }}</td>
        <td>{{ movement.timestamp }}</td>
        <td>{{ movement.text }}</td>
    </tr>
    {% endfor %}
</table>

{% endblock main %}

delta_bank_updated/delta_bank/bank_app/templates/bank_app/dashboard.html
{% extends "base.html" %}

{% block main %}

<p>Welcome, {{ user.customer.full_name }}.</p>

<h3>My accounts:</h3>
<table>
    <tr>
        <th>Account Number</th>
        <th>Account Name</th>
    </tr>
    {% for account in accounts %}
    <tr>
        <td><a href="{% url 'bank_app:account_details' account.pk %}">{{ account.pk }}</a></td>
        <td>{{ account.name }}</td>
    </tr>
    {% endfor %}
</table>
{% endblock main %}

delta_bank_updated/delta_bank/bank_app/templates/bank_app/error.html
{% extends "base.html" %}

{% block main %}

<p>Welcome, {% if user.is_staff %}{{ user.username }}{% else %}{{ user.customer.full_name }}{% endif %}.</p>

<h3>{{ title }}</h3>

<p>{{ error }}</p>

{% endblock main %}

delta_bank_updated/delta_bank/bank_app/templates/bank_app/inbox.html
{% extends "base.html" %}

{% block main %}

<h2>Inbox</h2>
<div>
    {% for message in messages %}
        <p>From: 
        <a href="{% url 'bank_app:message_detail' message.pk %}">{{ message.sender }} - {{ message.timestamp }}</a></p>
    {% endfor %}
</div>

<hr>

<h2>Send Message</h2>
<form method="post" action="{% url 'bank_app:message' %}">
    {% csrf_token %}
    <fieldset>
        {{ form.receiver }}
        {{ form.content }}
        <input type="submit" value="Send message"/>
    </fieldset>
    
</form>


{% endblock main %}

delta_bank_updated/delta_bank/bank_app/templates/bank_app/make_loan.html
{% extends "base.html" %}

{% block main %}
<form action="{% url 'bank_app:make_loan' %}" method="post">
    {% csrf_token %}
    <fieldset>
    <label>
        Name for loan
        <input name="name" type="text" />
    </label>
    <label>
        Amount
        <input name="amount" />
    </label>
    <button>Submit</button>
    </fieldset>
</form>
{% endblock main %}

delta_bank_updated/delta_bank/bank_app/templates/bank_app/make_transfer.html
{% extends "base.html" %}

{% block main %}
<form id="transfer_form" onsubmit="make_transfer(); return false;">
    {% csrf_token %}
    <fieldset>
        {{ form }}
        <input type="submit" value="Overføre"/>
    </fieldset>
    
</form>

{% load static %}  
<script src="{% static 'transfer.js' %}" type="text/javascript"></script>

{% endblock main %}

delta_bank_updated/delta_bank/bank_app/templates/bank_app/message.html
{% extends "base.html" %}

{% block main %}


<h2>Message Detail</h2>
<p><strong>From:</strong> {{ message.sender }}</p>
<p><strong>Date:</strong> {{ message.timestamp }}</p>

<p>{{ message.content }}</p>




{% endblock main %}

delta_bank_updated/delta_bank/bank_app/templates/bank_app/settings.html
{% extends "base.html" %}

{% block main %}

<h2>Settings</h2>

<h3>2 factor authentication</h3>

{% if otp_verified %}
<p>Your account has already multi factor authentication</p>
{% else %}
<p>Verify your account now:</p>


<form id="otp_form" onsubmit="get_code(); return false;">
    {% csrf_token %}
    <fieldset>
        {{ form }}
        <input type="hidden" id="user_id" name="user_id" value="{{user_id}}">
        <input type="hidden" id="email" name="email" value="{{email}}">
        <input type="submit" value="Get code"/>
    </fieldset>
</form>


<form id="otp_verify_form" onsubmit="verify_code(); return false;">

    {% csrf_token %}
    <fieldset>
        <div id="result">
        </div>
        {{ form }}
        <input type="hidden" id="user_id" name="user_id" value="{{user_id}}">
        <input type="text" id="token" name="token" placeholder="6 digit code">
        <input type="submit" value="verify code"/>
    </fieldset>
</form>


{% endif %}




{% load static %}  
<script src="{% static 'authenticate.js' %}" type="text/javascript"></script>

{% endblock main %}

delta_bank_updated/delta_bank/bank_app/templates/bank_app/staff_account_list_partial.html
<tbody id="account-list">
{% for account in accounts %}
    <tr>
        <td><a href="{% url 'bank_app:staff_account_details' account.pk %}">{{ account.pk }}</a></td>
        <td>{{ account.name }}</td>
        <td>{{ account.balance|floatformat:"2" }}</td>
    </tr>
{% endfor %}
</tbody>

delta_bank_updated/delta_bank/bank_app/templates/bank_app/staff_customer_details.html
{% extends "base.html" %}

{% block main %}

<h3>Customer Details</h3>

<form action="{% url 'bank_app:staff_customer_details' customer.pk %}" method="post">
    {% csrf_token %}
    <fieldset>
        {{ user_form.as_p }}
        {{ customer_form.as_p }}
    <button>Update User</button>
    </fieldset>
</form>

<table>
    <thead>
        <tr>
            <th>Account Number</th>
            <th>Account Name</th>
            <th>Account Balance</th>
        </tr>
    </thead>
    <tbody
        id="account-list"
        hx-swap="outerHTML"
        hx-get="{% url 'bank_app:staff_account_list_partial' customer.pk %}"
        hx-trigger="load">
    </tbody>
</table>

<h3>Create New Account</h3>
<form action="{% url 'bank_app:staff_new_account_partial' customer.user.pk %}" method="post">
    {% csrf_token %}
    <fieldset>
        {{ new_account_form.as_p }}
    <button>Create Account</button>
    </fieldset>
</form>

{% endblock main %}

delta_bank_updated/delta_bank/bank_app/templates/bank_app/staff_dashboard.html
{% extends "base.html" %}

{% block main %}

<p>Welcome, {{ user }}.</p>

<fieldset>
    <label>Customer Look Up</label>
    <input name="search_term"
           placeholder="Search on customer data"
           class="form-control"
           type="text"
           hx-post="{% url 'bank_app:staff_search_partial' %}"
           hx-trigger="keyup changed delay:500ms"
           hx-target="#search-results"
           hx-indicator=".htmx-indicator"
    />
    {% csrf_token %}
</fieldset>

<table>
    <thead>
        <th>ID</th>
        <th>Persal ID</th>
        <th>Name</th>
        <th>Phone</th>
        <th>Email</th>
    </thead>
    <tbody id="search-results">
    </tbody>
</table>

{% endblock main %}

delta_bank_updated/delta_bank/bank_app/templates/bank_app/staff_new_customer.html
{% extends "base.html" %}

{% block main %}
<form action="{% url 'bank_app:staff_new_customer' %}" method="post">
    {% csrf_token %}
    <fieldset>
        {{ new_user_form }}
        {{ customer_form }}
    <button>Create User</button>
    </fieldset>
</form>
{% endblock main %}

delta_bank_updated/delta_bank/bank_app/templates/bank_app/staff_search_partial.html
{% for customer in customers %}
<tr>
    <td><a href="{% url 'bank_app:staff_customer_details' customer.pk %}">{{ customer.pk }}</a></td>
    <td>{{ customer.personal_id }}</td>
    <td>{{ customer.full_name }}</td>
    <td>{{ customer.phone }}</td>
    <td>{{ customer.user.email }}</td>
</tr>
{% endfor %}

delta_bank_updated/delta_bank/bank_app/templates/bank_app/transaction_details.html
{% extends "base.html" %}

{% block main %}

<p>Welcome, {{ user.customer.full_name }}.</p>

<h3>Transaction Details</h3>

<table>
    <tr>
        <th>Account Number</th>
        <th>Transaction UUID</th>
        <th>Amount</th>
        <th>Date and Time</th>
        <th>Text</th>
    </tr>
    {% for movement in movements %}
    <tr>
        <td>{{ movement.account }}</td>
        <td>{{ movement.transaction }}</td>
        <td>{{ movement.amount|floatformat:"2" }}</td>
        <td>{{ movement.timestamp }}</td>
        <td>{{ movement.text }}</td>
    </tr>
    {% endfor %}
</table>

{% endblock main %}